[env:lilygo-tsim7670g-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_speed = 921600
monitor_speed = 115200

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L

; USB CDC (important for S3)
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0

; Required for LILYGO T-SIM7670G-S3
lib_deps =
    vshymanskyy/TinyGSM @ ^0.12.0
    bblanchon/ArduinoJson @ ^7.0.0
    mikalhart/TinyGPSPlus @ ^1.1.0
    electroniccats/MPU6050 @ ^1.4.4
